In [1]:
import os
os.chdir("../../")

In [2]:
os.getcwd()

'/home/ec2-user/environment/transithealth'

In [3]:

import pandas as pd
import requests
from pipeline.utils.data import extract_data_portal_dates

In [8]:
dataset_json_url = "https://data.cityofchicago.org/resource/5neh-572f.json"
query = """
SELECT
    station_id,
    stationname,
    date,
    daytype,
    rides
WHERE
    date >= "2019-01-01" AND date <= "2021-02-28"
LIMIT 115000
"""
r = requests.get(dataset_json_url, params={"$query": query})
df = pd.DataFrame(r.json())
print(df.shape[0])
df

113001

,station_id,stationname,date,daytype,rides
0,40010,Austin-Forest Park,2019-01-01T00:00:00.000,U,576
1,40020,Harlem-Lake,2019-01-01T00:00:00.000,U,981
2,40030,Pulaski-Lake,2019-01-01T00:00:00.000,U,835
3,40040,Quincy/Wells,2019-01-01T00:00:00.000,U,929
4,40050,Davis,2019-01-01T00:00:00.000,U,1207
...,...,...,...,...,...
112996,41660,Lake/State,2021-02-28T00:00:00.000,U,2040
112997,41670,Conservatory,2021-02-28T00:00:00.000,U,284
112998,41680,Oakton-Skokie,2021-02-28T00:00:00.000,U,94
112999,41690,Cermak-McCormick Place,2021-02-28T00:00:00.000,U,195
113000,41700,Washington/Wabash,2021-02-28T00:00:00.000,U,1203

In [5]:
print(type(df["date"][0]))

<class 'str'>

In [ ]:
#def transformDate(old_date):

In [ ]:
#df['ymd'] = transformDate(df['date'])

In [6]:
df = extract_data_portal_dates(df, col="date", prefix="")

In [9]:
df[0:50]

   station_id               stationname                     date daytype rides
0       40010        Austin-Forest Park  2019-01-01T00:00:00.000       U   576
1       40020               Harlem-Lake  2019-01-01T00:00:00.000       U   981
2       40030              Pulaski-Lake  2019-01-01T00:00:00.000       U   835
3       40040              Quincy/Wells  2019-01-01T00:00:00.000       U   929
4       40050                     Davis  2019-01-01T00:00:00.000       U  1207
5       40060            Belmont-O'Hare  2019-01-01T00:00:00.000       U  1608
6       40070          Jackson/Dearborn  2019-01-01T00:00:00.000       U  1495
7       40080                  Sheridan  2019-01-01T00:00:00.000       U  1839
8       40090               Damen-Brown  2019-01-01T00:00:00.000       U   643
9       40100                     Morse  2019-01-01T00:00:00.000       U  2021
10      40120               35th/Archer  2019-01-01T00:00:00.000       U   754
11      40130                      51st  2019-01-01T00:00:00.000       U   414
12      40140           Dempster-Skokie  2019-01-01T00:00:00.000       U   378
13      40150            Pulaski-Cermak  2019-01-01T00:00:00.000       U   527
14      40160         LaSalle/Van Buren  2019-01-01T00:00:00.000       U   239
15      40170              Ashland-Lake  2019-01-01T00:00:00.000       U   485
16      40180      Oak Park-Forest Park  2019-01-01T00:00:00.000       U   356
17      40190         Sox-35th-Dan Ryan  2019-01-01T00:00:00.000       U  1671
18      40200           Randolph/Wabash  2019-01-01T00:00:00.000       U     0
19      40210              Damen-Cermak  2019-01-01T00:00:00.000       U   394
20      40220       Western-Forest Park  2019-01-01T00:00:00.000       U   618
21      40230                Cumberland  2019-01-01T00:00:00.000       U  1038
22      40240                      79th  2019-01-01T00:00:00.000       U  3342
23      40250  Kedzie-Homan-Forest Park  2019-01-01T00:00:00.000       U   978
24      40260                State/Lake  2019-01-01T00:00:00.000       U  3359
25      40270                      Main  2019-01-01T00:00:00.000       U   350
26      40280              Central-Lake  2019-01-01T00:00:00.000       U   706
27      40290              Ashland/63rd  2019-01-01T00:00:00.000       U   370
28      40300                   Indiana  2019-01-01T00:00:00.000       U   274
29      40310            Western-Orange  2019-01-01T00:00:00.000       U   962
30      40320        Division/Milwaukee  2019-01-01T00:00:00.000       U  2282
31      40330               Grand/State  2019-01-01T00:00:00.000       U  8547
32      40340                    Berwyn  2019-01-01T00:00:00.000       U  1335
33      40350               UIC-Halsted  2019-01-01T00:00:00.000       U   981
34      40360                 Southport  2019-01-01T00:00:00.000       U  1115
35      40370       Washington/Dearborn  2019-01-01T00:00:00.000       U  3436
36      40380                Clark/Lake  2019-01-01T00:00:00.000       U  3709
37      40390               Forest Park  2019-01-01T00:00:00.000       U   889
38      40400                     Noyes  2019-01-01T00:00:00.000       U   157
39      40420             Cicero-Cermak  2019-01-01T00:00:00.000       U   518
40      40430       Clinton-Forest Park  2019-01-01T00:00:00.000       U   780
41      40440         California-Cermak  2019-01-01T00:00:00.000       U   425
42      40450             95th/Dan Ryan  2019-01-01T00:00:00.000       U  4008
43      40460          Merchandise Mart  2019-01-01T00:00:00.000       U   955
44      40470                    Racine  2019-01-01T00:00:00.000       U   601
45      40480               Cicero-Lake  2019-01-01T00:00:00.000       U   639
46      40490           Grand/Milwaukee  2019-01-01T00:00:00.000       U  1341
47      40510   Garfield-South Elevated  2019-01-01T00:00:00.000       U   235
48      40520                    Foster  2019-01-01T00:00:00.000       U   165
49      40530                  Diversey  2019-01-01T00:00:00.000       U  1352

In [11]:
dataset_json_url = "https://data.cityofchicago.org/resource/5neh-572f.json"
query = """
SELECT
    station_id,
    stationname,
    date,
    daytype,
    rides
WHERE
    date >= "2001-01-01" AND date <= "2021-02-28" AND
    stationname IN ('Howard', 'Wilson', 'Belmont', 'Fullerton', 'Merchandise Mart', 'Ashland', 'Roosevelt', 'Clinton', 'Clark/Lake', 'State/Lake', 'Lake', 'Washington', 'Washington/Wabash', 'Adams/Wabash', 'Jackson', 'Harold Washington Library', 'LaSalle/Van Buren', 'Quincy', 'Washington/Wells')
LIMIT 75000
"""
r2 = requests.get(dataset_json_url, params={"$query": query})
df2 = pd.DataFrame(r2.json())
print(df2.shape[0])
df2[0:50]

74993

   station_id        stationname                     date daytype  rides
0       40540             Wilson  2017-12-22T00:00:00.000       W   4861
1       40260         State/Lake  2017-12-06T00:00:00.000       W  12646
2       40380         Clark/Lake  2017-12-20T00:00:00.000       W  20358
3       40730   Washington/Wells  2017-12-16T00:00:00.000       A   1256
4       41220          Fullerton  2017-12-28T00:00:00.000       W   4600
5       40160  LaSalle/Van Buren  2017-12-05T00:00:00.000       W   3326
6       40680       Adams/Wabash  2017-12-06T00:00:00.000       W   7234
7       41400          Roosevelt  2017-12-31T00:00:00.000       U   4775
8       40540             Wilson  2017-12-17T00:00:00.000       U   2858
9       40540             Wilson  2017-12-12T00:00:00.000       W   6215
10      40260         State/Lake  2017-12-11T00:00:00.000       W  12074
11      40900             Howard  2017-12-29T00:00:00.000       W   4159
12      40730   Washington/Wells  2017-12-04T00:00:00.000       W   8589
13      40900             Howard  2017-12-31T00:00:00.000       U   2692
14      40460   Merchandise Mart  2017-12-30T00:00:00.000       A   1028
15      40260         State/Lake  2017-12-10T00:00:00.000       U   4406
16      40460   Merchandise Mart  2017-12-14T00:00:00.000       W   7894
17      40460   Merchandise Mart  2017-12-01T00:00:00.000       W   7965
18      41400          Roosevelt  2017-12-27T00:00:00.000       W   6404
19      40540             Wilson  2017-12-09T00:00:00.000       A   4228
20      41700  Washington/Wabash  2017-12-09T00:00:00.000       A   5749
21      40730   Washington/Wells  2017-12-30T00:00:00.000       A    765
22      40260         State/Lake  2017-12-17T00:00:00.000       U   4532
23      41700  Washington/Wabash  2017-12-14T00:00:00.000       W  10228
24      40680       Adams/Wabash  2017-12-02T00:00:00.000       A   3393
25      40460   Merchandise Mart  2017-12-22T00:00:00.000       W   4400
26      40680       Adams/Wabash  2017-12-03T00:00:00.000       U   2463
27      40380         Clark/Lake  2017-12-10T00:00:00.000       U   4973
28      40730   Washington/Wells  2017-12-25T00:00:00.000       U    334
29      40380         Clark/Lake  2017-12-03T00:00:00.000       U   5682
30      41400          Roosevelt  2017-12-14T00:00:00.000       W  10434
31      40680       Adams/Wabash  2017-12-05T00:00:00.000       W   7130
32      40380         Clark/Lake  2017-12-22T00:00:00.000       W  15598
33      40460   Merchandise Mart  2017-12-13T00:00:00.000       W   8337
34      41700  Washington/Wabash  2017-12-25T00:00:00.000       U   1205
35      41220          Fullerton  2017-12-17T00:00:00.000       U   4237
36      40730   Washington/Wells  2017-12-24T00:00:00.000       U    553
37      40540             Wilson  2017-12-03T00:00:00.000       U   3193
38      41400          Roosevelt  2017-12-09T00:00:00.000       A   7331
39      40730   Washington/Wells  2017-12-31T00:00:00.000       U    604
40      40680       Adams/Wabash  2017-12-16T00:00:00.000       A   2907
41      41700  Washington/Wabash  2017-12-27T00:00:00.000       W   6092
42      41700  Washington/Wabash  2017-12-29T00:00:00.000       W   7313
43      41700  Washington/Wabash  2017-12-18T00:00:00.000       W  10378
44      41700  Washington/Wabash  2017-12-19T00:00:00.000       W  11253
45      40460   Merchandise Mart  2017-12-17T00:00:00.000       U   1082
46      40900             Howard  2017-12-10T00:00:00.000       U   2967
47      40460   Merchandise Mart  2017-12-27T00:00:00.000       W   3588
48      41400          Roosevelt  2017-12-18T00:00:00.000       W   9385
49      40380         Clark/Lake  2017-12-21T00:00:00.000       W  19322

In [5]:
df2[0:50]

   station_id        stationname                     date daytype  rides
0       40540             Wilson  2017-12-22T00:00:00.000       W   4861
1       40260         State/Lake  2017-12-06T00:00:00.000       W  12646
2       40380         Clark/Lake  2017-12-20T00:00:00.000       W  20358
3       40730   Washington/Wells  2017-12-16T00:00:00.000       A   1256
4       41220          Fullerton  2017-12-28T00:00:00.000       W   4600
5       40160  LaSalle/Van Buren  2017-12-05T00:00:00.000       W   3326
6       40680       Adams/Wabash  2017-12-06T00:00:00.000       W   7234
7       41400          Roosevelt  2017-12-31T00:00:00.000       U   4775
8       40540             Wilson  2017-12-17T00:00:00.000       U   2858
9       40540             Wilson  2017-12-12T00:00:00.000       W   6215
10      40260         State/Lake  2017-12-11T00:00:00.000       W  12074
11      40900             Howard  2017-12-29T00:00:00.000       W   4159
12      40730   Washington/Wells  2017-12-04T00:00:00.000       W   8589
13      40900             Howard  2017-12-31T00:00:00.000       U   2692
14      40460   Merchandise Mart  2017-12-30T00:00:00.000       A   1028
15      40260         State/Lake  2017-12-10T00:00:00.000       U   4406
16      40460   Merchandise Mart  2017-12-14T00:00:00.000       W   7894
17      40460   Merchandise Mart  2017-12-01T00:00:00.000       W   7965
18      41400          Roosevelt  2017-12-27T00:00:00.000       W   6404
19      40540             Wilson  2017-12-09T00:00:00.000       A   4228
20      41700  Washington/Wabash  2017-12-09T00:00:00.000       A   5749
21      40730   Washington/Wells  2017-12-30T00:00:00.000       A    765
22      40260         State/Lake  2017-12-17T00:00:00.000       U   4532
23      41700  Washington/Wabash  2017-12-14T00:00:00.000       W  10228
24      40680       Adams/Wabash  2017-12-02T00:00:00.000       A   3393
25      40460   Merchandise Mart  2017-12-22T00:00:00.000       W   4400
26      40680       Adams/Wabash  2017-12-03T00:00:00.000       U   2463
27      40380         Clark/Lake  2017-12-10T00:00:00.000       U   4973
28      40730   Washington/Wells  2017-12-25T00:00:00.000       U    334
29      40380         Clark/Lake  2017-12-03T00:00:00.000       U   5682
30      41400          Roosevelt  2017-12-14T00:00:00.000       W  10434
31      40680       Adams/Wabash  2017-12-05T00:00:00.000       W   7130
32      40380         Clark/Lake  2017-12-22T00:00:00.000       W  15598
33      40460   Merchandise Mart  2017-12-13T00:00:00.000       W   8337
34      41700  Washington/Wabash  2017-12-25T00:00:00.000       U   1205
35      41220          Fullerton  2017-12-17T00:00:00.000       U   4237
36      40730   Washington/Wells  2017-12-24T00:00:00.000       U    553
37      40540             Wilson  2017-12-03T00:00:00.000       U   3193
38      41400          Roosevelt  2017-12-09T00:00:00.000       A   7331
39      40730   Washington/Wells  2017-12-31T00:00:00.000       U    604
40      40680       Adams/Wabash  2017-12-16T00:00:00.000       A   2907
41      41700  Washington/Wabash  2017-12-27T00:00:00.000       W   6092
42      41700  Washington/Wabash  2017-12-29T00:00:00.000       W   7313
43      41700  Washington/Wabash  2017-12-18T00:00:00.000       W  10378
44      41700  Washington/Wabash  2017-12-19T00:00:00.000       W  11253
45      40460   Merchandise Mart  2017-12-17T00:00:00.000       U   1082
46      40900             Howard  2017-12-10T00:00:00.000       U   2967
47      40460   Merchandise Mart  2017-12-27T00:00:00.000       W   3588
48      41400          Roosevelt  2017-12-18T00:00:00.000       W   9385
49      40380         Clark/Lake  2017-12-21T00:00:00.000       W  19322